### ISSUE TITLE
New version of ImageMagick

### ISSUE THREAD

**Issue by dgallichan** [dgallichan/retroMoCoBox#7]
Since ImageMagick version 7, the syntax has changed from 'convert' to 'magick'. Need to handle this properly in the retroMoCoBox!

**Comment by dgallichan** [comment]
This was fixed at some point :)

**Comment by leonleon33156** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
